doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        types:
            ulid: App\Shared\Infrastructure\Database\Types\UlidType
            email: App\Shared\Infrastructure\Database\Types\EmailType
            phone_number: App\Shared\Infrastructure\Database\Types\PhoneNumberType
            client_first_name: App\Clients\Infrastructure\Database\Types\ClientFirstNameType
            client_last_name: App\Clients\Infrastructure\Database\Types\ClientLastNameType
            client_age: App\Clients\Infrastructure\Database\Types\ClientAgeType
            client_credit_info_fico_score: App\Clients\Infrastructure\Database\Types\ClientCreditInfoFICOScoreType
            client_credit_info_ssn: App\Clients\Infrastructure\Database\Types\ClientCreditInfoSSNType
            client_credit_info_income: App\Clients\Infrastructure\Database\Types\ClientCreditInfoIncomeType
            product_name: App\Products\Infrastructure\Database\Types\ProductNameType
            interest_rate: App\Products\Infrastructure\Database\Types\InterestRateType
            loan_term: App\Products\Infrastructure\Database\Types\LoanTermType
            loan_amount: App\Products\Infrastructure\Database\Types\LoanAmountType

    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            Clients:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Clients/Infrastructure/Database/ORM'
                prefix: 'App\Clients\Domain\Entity'
                alias: Clients
            Products:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Products/Infrastructure/Database/ORM'
                prefix: 'App\Products\Domain\Entity'
                alias: Products
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
