version: '3.8'

services:
  americor_test_php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
    container_name: americor_php
    volumes:
      - ./:/var/www
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    ports:
      - "9003:9003"
    networks:
      - americor_test_network
    depends_on:
      - americor_test_mysql
    healthcheck:
      test: ["CMD-SHELL", "php -v || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 3
    command: >
      sh -c "
        composer install &&
        php bin/console doctrine:migrations:migrate --no-interaction &&
        php bin/console doctrine:migrations:migrate --no-interaction --env=test &&
        php-fpm
      "

  americor_test_mysql:
    image: mysql:latest
    container_name: americor_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: americor
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql-init:/docker-entrypoint-initdb.d
      - americor_test_mysql_data:/var/lib/mysql
    networks:
      - americor_test_network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 5

  americor_test_nginx:
    image: nginx:latest
    container_name: americor_nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - americor_test_php
    networks:
      - americor_test_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://americor_php:9003 || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 5

networks:
  americor_test_network:
    driver: bridge

volumes:
  americor_test_mysql_data:
